### ISSUE TITLE
Webpacks plugins that rely on "optimize-chunk-assets" not working

### ISSUE THREAD

**Issue by juanjoDiaz** [codymikol/karma-webpack#177]
## **BEFORE YOU SUBMIT** please read the following:

**I'm submitting a bug report**

**Webpack version:**
1.12.9

**Webpack Karma version**:
1.7.0

**Karma version**:
0.13.15

**Please tell us about your environment:**
OSX 10.x

**Current behavior:**
I'm using [webpack polyfill service plugin](https://www.npmjs.com/package/webpack-polyfill-service-plugin) to add some polyfills to my library. It works flawlessly when building my library using webpack but that when I run karma, the plugin doesn't work.
I can see that the issue comes from the plugin relying on 

```
compilation.plugin("optimize-chunk-assets", function(chunks, callback) {
    chunks.forEach(function(chunk) {
        if (!chunk.initial) return;
        // add polyfills to the assets
    });
}):
```

and the problem is that chunks is an empty array so if the callback is in the `forEach` it's never called and in any case the polyfills are never added.

This affect any other plugin that uses the same approach to add code to the assets.

**Expected/desired behavior:**
Chunks contain all the chunks and the polyfills are added to the intial chunk.

**Comment by d3viant0ne** [comment]
@juanjoDiaz - Support for chunks, multiple entries, file source maps and a few other things are slated for v3.

I'll try to address this if it makes sense though it's worth noting, karma-webpack v3 will require webpack 2.x.

If it's possible to get this into a small demo repo like https://github.com/Silviu-Marian/karma-webpack-pr69 that would make it much more likely that I can get this addressed and proper validations written to prevent regressions.

**Comment by benweiser** [comment]
I would imagine most builds are going to take advantage of many Webpack's plugins that are unsupported. Is the only solution here to create a separate webpack.config just for karma? +1 for documenting this, it took me delving down a rabbit hole to find my way here to discover I have to rewrite my config because Chunks & Extract Text Plugin aren't supported. Does anyone have an example of a workaround?

**Comment by codymikol** [comment]
As karma is now deprecated and coming up on EOL, we are no longer planning on any significant enhancements to this project and are instead going to focus on security updates, stability, and a migration path forward as karma's lifecycle comes to an end.

Thank you for supporting and using this project!
