### ISSUE TITLE
webpack silent mode

### ISSUE THREAD

**Issue by deepsweet** [codymikol/karma-webpack#26]
Hi.

With this in config:

``` javascript
webpackServer: {
    progress: false,
    stats: false,
    debug: false
},
```

I'm still getting these messages:

```
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
webpack: bundle is now VALID.
LOG: 'ok'
```

Is there an implemented way to completely turn it off?

**Comment by pwang2** [comment]
I am using isparta-loader,  could you explain where should i put the quiet property?  I tried webpackMiddleWare it does not work.

**Comment by deepsweet** [comment]
[it should work](https://webpack.github.io/docs/webpack-dev-middleware.html#quiet)

**Comment by pwang2** [comment]
@deepsweet , like [this](https://gist.github.com/pwang2/ba6109ec07427abdef117c9d0ccceb43#file-karma-config-js-L43)?  

Still get bundle information.

**Comment by pwang2** [comment]
got it!   it should be put outside webpack:{}..  Thanks for your help though.

**Comment by deepsweet** [comment]
👍
