### ISSUE TITLE
Recompilation of entire bundle after each change takes too long.

### ISSUE THREAD

**Issue by josh08h** [codymikol/karma-webpack#399]
Recompiling the test bundle after every change and rerunning the entire suite is taking a long time.

The majority of the time taken is recompiling the entire test bundle again from scratch. Would it be a lot of work to implement some sort of webpack-dev-server hot compilation? That way, we could just recompile what is needed as opposed to recompiling from scratch.

**Comment by fa-hmad** [comment]
I too badly need this. I've tried many schemes but they are very slow. It's the rebuilds that kill us.

**Comment by rynclark** [comment]
Can you provide a sample repo with your configuration if possible? Theoretically if each of your test files is an entry it shouldn’t recompile them all on save, only the charged files. An example would be a good start to look at why it isn’t working as expected.

**Comment by stevenvachon** [comment]
For me, it's "commons.js" that takes forever to build; which I'm guessing is the code being tested.

**Comment by stevenvachon** [comment]
My recompilation times with Webpack alone are much faster than with Karma, which leads me to believe that the performance loss is due to this plugin.

**Comment by fa-hmad** [comment]
@stevenvachon are you compiling your tests in a single bundle? or are they different entries in terms of webpack?

**Comment by stevenvachon** [comment]
@fa-hmad all entries come from karma. I exclude chunking configs while testing.

**Comment by josh08h** [comment]
@fa-hmad Single bundle

**Comment by josh08h** [comment]
I have decided to run `webpack-dev-server` and `karma` processes concurrently as opposed to using `karma-webpack`. Recompilation on file save has gone from 20seconds to 0.2seconds.

**Comment by roerdinkholder** [comment]
> My recompilation times with Webpack alone are much faster than with Karma, which leads me to believe that the performance loss is due to this plugin.
> 
> If I disable Webpack's `devtool` (which I had set to "inline-source-map"), recompilation is _much_ faster. Perhaps what's happening is this plugin is causing Webpack to unnecessarily reprocess source maps for files that have not been changed.

This remark helped me find a solution for my very slow rebuilds. I initially tested whether this resolved my problem as well by setting `devtool: false` in my karma configuration. Rebuild times went down from 30s to 0.5s at the expense of source maps. After a little bit of reading up, I ended up using `devtool: 'eval-source-map'`. My rebuild time stayed below 1 second, and I have my sourcemaps back!

**Comment by matyasf** [comment]
For me deleting the `cache` option from webpack config caused a very significant speedup (12 sec -> 0.8sec)

**Comment by codymikol** [comment]
As karma is now deprecated and coming up on EOL, we are no longer planning on any significant enhancements to this project and are instead going to focus on security updates, stability, and a migration path forward as karma's lifecycle comes to an end.

Thank you for supporting and using this project!
