### ISSUE TITLE
writeToDisk option used by webpack-dev-middleware isn't supported

### ISSUE THREAD

**Issue by sergei-startsev** [codymikol/karma-webpack#405]
* Operating System: Win10
* Node Version: 10
* NPM Version: 6
* webpack Version: 4
* karma-webpack Version: 4.0.0-rc.6

### Expected Behavior

[writetodisk](https://github.com/webpack/webpack-dev-middleware#writetodisk) option should instructs `webpack-dev-middleware` to write files to the configured location on disk as specified in webpack config file.

### Actual Behavior

`karma-webpack` ignores output path specified in webpack configuration and overrides it to the following path:

https://github.com/webpack-contrib/karma-webpack/blob/11cb4fb2af12271bade16915066be47cbc2e85d7/src/karma-webpack.js#L93-L98

### Code

```js
// karma.conf.js
webpack: {
  output: {
    // output path is ignored by karma-webpack
    path: path.join(__dirname, './dist'),
  },
},
webpackMiddleware: {
  // https://github.com/webpack/webpack-dev-middleware#writetodisk
  writeToDisk: true
}, 
```

### How Do We Reproduce?
See `karma.conf.js` above.

**Comment by codymikol** [comment]
As karma is now deprecated and coming up on EOL, we are no longer planning on any significant enhancements to this project and are instead going to focus on security updates, stability, and a migration path forward as karma's lifecycle comes to an end.

Thank you for supporting and using this project!
