### ISSUE TITLE
Support external source-maps

### ISSUE THREAD

**Issue by codymikol** [codymikol/karma-webpack#485]
I'm making one issue to consolidate all of the existing reports that source maps do not work with karma-webpack

## Aggregated Information

* Currently using `devtool: 'inline-source-map'` functions, but the external `devtool: 'source-map'` fails.
* There is a possibility of leveraging the webpack `writeToDisk` option to support this, but that is blocked by #405 
* TS files potentially don't even work with the inline-source-map

## Current plan

Ensure that karma-webpack works out of the box will all of the built in devtool options and triage why different options might cause the plugin to fail.

documentation on these here: https://webpack.js.org/configuration/devtool/

## Previous Issues

#224 
#176
#104

**Comment by AprilArcus** [comment]
It seems that karma-sourcemap-loader is attempting resolve source maps relative to the entrypoint, rather than to the corresponding build artifact in the temp directory.

**Comment by top-master** [comment]
In my case, I was able to get exact line number by combining two things.

* Installing the `karma-source-map-support` package (and adding "source-map-support" to frameworks in `karma.conf.js`).
* Setting WebPacks `devtool` to `inline-source-map` (as above package does not seem to work well with other options).

**Comment by renaldas-kerpe-arria** [comment]
Is this still being worked on?

**Comment by codymikol** [comment]
I don't believe so

**Comment by sergei-startsev** [comment]
If you're looking for mapped stacktraces for failed tests with external sourcemaps (`devtool: 'source-map'`), you may find this useful: https://github.com/sergei-startsev/karma-stacktrace/

**Comment by codymikol** [comment]
As karma is now deprecated and coming up on EOL, we are no longer planning on any significant enhancements to this project and are instead going to focus on security updates, stability, and a migration path forward as karma's lifecycle comes to an end.

Thank you for supporting and using this project!
