### ISSUE TITLE
Webpack multicompiler support is broken as of karma-webpack@^5.0.0

### ISSUE THREAD

**Issue by meyer** [codymikol/karma-webpack#511]
* Operating System: macOS 11
* Node Version: 12
* NPM Version: yarn 1
* webpack Version: 5
* karma-webpack Version: 5

### Expected Behavior

`webpackOptions` can (continue to) be an array of webpack configs.

### Actual Behavior

I get this error:

```
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property '1'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry?, externals?, infrastructureLogging?, loader?, mode?, module?, name?, node?, optimization?, output?, parallelism?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, serve?, stats?, target?, watch?, watchOptions? }
```

I suspect a webpack-merge-type operation is turning my array of configs into an object with numbers as keys.

Here’s how v4 managed multiconfigs: https://github.com/ryanclark/karma-webpack/blob/48878eb/src/karma-webpack.js#L64-L69

### How Do We Reproduce?

Provide an array of configs as the `webpack` option in your karma config file.

**Comment by codymikol** [comment]
Thanks for opening an issue, would you be interested in working on a test case or fix for this? I can assist you in getting that merged and into a release.

**Comment by meyer** [comment]
If I get a sec this week I’ll give it a go. I’m currently evaluating karma replacements at the moment thoughm so this may end up falling through the cracks.

**Comment by codymikol** [comment]
As karma is now deprecated and coming up on EOL, we are no longer planning on any significant enhancements to this project and are instead going to focus on security updates, stability, and a migration path forward as karma's lifecycle comes to an end.

Thank you for supporting and using this project!
