### ISSUE TITLE
karma-webpack 5.0 No longer notified of compilation starting

### ISSUE THREAD

**Issue by Roaders** [codymikol/karma-webpack#513]
* Operating System: windows
* Node Version: 14
* NPM Version: 6
* webpack Version: 5
* karma-webpack Version: 5

### Expected Behavior

When watching tests and a change is made we should be notified that a new build is starting. This used to take the form:

```
[wdm] Compiling...
```

### Actual Behavior

No notification is posted

This seems to be a side effect of removing Webpack Dev Middleware but it is a major pain for us. The webpack builds are up to a minute. This feels so much longer with no indication that a build has actually started.

**Comment by AprilArcus** [comment]
You could re-implement this with

```
new webpack.ProgressPlugin((percent, message) => {
  if (percent <= 0) {
    console.info('webpack starting')
  }
})
```

@ryanclark is this something we should include by default?

**Comment by codymikol** [comment]
As karma is now deprecated and coming up on EOL, we are no longer planning on any significant enhancements to this project and are instead going to focus on security updates, stability, and a migration path forward as karma's lifecycle comes to an end.

Thank you for supporting and using this project!
