### ISSUE TITLE
Issue with Webpack 5 unable to find file 404 (works with webpack 4)

### ISSUE THREAD

**Issue by ankitdadhich** [codymikol/karma-webpack#546]
* Operating System: Windows 10
* Node Version: 16.15.1
* NPM Version: 8.11.0
* webpack Version: 5.74.0
* karma-webpack Version: 5.0.0

### Code

```Debug Log ```
packages.json https://gist.github.com/ankitdadhich/24c5e031a1a6ff447a1418f4a27472bb
karma test debug log error with webpack 5  https://gist.github.com/ankitdadhich/0a046e4e843237137b7340c6a0edb719
karma test debug log working sample with webpack 4 https://gist.github.com/ankitdadhich/3e452bfc2c30c965531f17eb81f8c23f
webpack.config.js https://gist.github.com/ankitdadhich/df1db0ff4483845c640eae3c46cbe174

### How Do We Reproduce?
Issue with Webpack 5. Just use above latest versions of webpack 5

**Comment by juburr** [comment]
My project also started spitting back 404 errors after upgrading to webpack 5. They were coming from unit tests utilizing axios-mock-adapter. I had to add the following lines to my dev mode webpack configuration to get it working:

```javascript
optimization: {
    runtimeChunk: false,
    splitChunks: false
},
```

Karma-webpack works great with webpack v5 after that.

**Comment by ankitdadhich** [comment]
@juburr i get this error 
```
[webpack-cli] Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.module has an unknown property 'optimization'. These properties are valid:
   object { defaultRules?, exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, generator?, noParse?, parser?, rules?, strictExportPresence?, strictThisContextOnImports?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, unsafeCache?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp? }
   -> Options affecting the normal modules (`NormalModuleFactory`).
error Command failed with exit code 2.
```
