### ISSUE TITLE
Release 5.0.1

### ISSUE THREAD

**Issue by codymikol** [codymikol/karma-webpack#584]
I've brought all the dependencies of this repo up to date and gotten the `npm audit` down to 0 known vulnerabilities, I'd like to ship out a hotfix release. Thanks for assisting @alexander-akait !

**Comment by codymikol** [comment]
Ryan never had the opportunity to go over the release process before handing this repo over to me, so if you need any assistance or help from me, feel free to reach me via this issue, or shoot me an email over at hi@codymikol.com

**Comment by alexander-akait** [comment]
Can you write me your npm name at sheo13666q@gmail.com? I will do release right now, but I want you to be able to do this yourself in the future

**Comment by alexander-akait** [comment]
https://github.com/codymikol/karma-webpack/releases/tag/v5.0.1

**Comment by y1j2x34** [comment]
After updating to the latest patch version, I encountered an issue where the minimum required version of Node.js has been changed from >=10 to >=18 (189a8e3f0e794429cb73df3a8c11140c498519be).  And this change wasn't mentioned in the release notes.

**Comment by codymikol** [comment]
You're right, apologies on that, I'll see if I can continue to support >= 10 in a hotfix and then cut a major release that changes the node version.

**Comment by codymikol** [comment]
I opened another ticket to take care of that when I can, closing this as it is complete, thanks @alexander-akait !
