### ISSUE TITLE
Webpack configuration

### ISSUE THREAD

**Issue by uninstallit** [codymikol/karma-webpack#590]
Hey there! If you need support, help, or advice then this is not the place to ask.
Please visit [StackOverflow](https://stackoverflow.com/questions/tagged/webpack)
or [the Webpack Gitter](https://gitter.im/webpack/webpack) instead.

Hello, I was wondering if the library should still be used to bundle all the test in one - or karma fixed their issues. 

If this plugin is still relevant - do I need to provide an additional webpack config or the defaults that are merged are sufficient?  

I am working with an angular typescript project.

**Comment by codymikol** [comment]
Hey there! If you need support, help, or advice then this is not the place to ask.
Please visit [StackOverflow](https://stackoverflow.com/questions/tagged/webpack)
or [the Webpack Gitter](https://gitter.im/webpack/webpack) instead.
