### ISSUE TITLE
Web-server always serve cached files to karma runners

### ISSUE THREAD

**Issue by okonet** [codymikol/karma-webpack#9]
It looks like the webpack-dev-server always serve a cached versions of my specs when running with `grunt-watch` and `karma:unit:run` mode. I've already tried to set `cache: false` in karma's webpack config but it didn't help. 

Is there something I'm missing here?

**Comment by johanneslumpe** [comment]
@sokra Just came across this - does this issue also include karma running tests twice? Once on save (old tests) and once after the new tests are compiled. Could this be related to karma-webpack or is that just a karma issue? Sorry for posting here in case this doesn't belong here.

**Comment by QuantumInformation** [comment]
karma start works ok, but have the caching issue with Webstorm
